BlogSitesi/Models/DataContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace BlogSitesi.Models
{
    public class DataContext:DbContext
    {
        //public DataContext():base("BlogDatabase") { }
        //Veritabanı işlemlerinde Kullanılacak veriler
        public DbSet<Private> admin { get; set; }

        public DbSet<MakaleMenu> makaleMenus { get; set; }
    }
}

BlogSitesi/Models/KategoriMenu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogSitesi.Models
{
    public class KategoriMenu
    {
        public int Id { get; set; }
        public string KategoriAdi { get; set; }
    }
}

BlogSitesi/Models/MakaleMenu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogSitesi.Models
{
    public class MakaleMenu
    {
        public int Id { get; set; }
        public string image { get; set; }
        public string makaleBaslik { get; set; }
        public string altBaslik { get;set; }

        public string makaleTarih { get; set; }
        public string makaleIcerik { get; set; }

        public bool makaleButonIceriyormu { get; set; }
        public string buttonText { get; set; }
        public string buttonLink { get; set; }
    }
}

BlogSitesi/Models/ModelManager.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogSitesi.Models
{
    public class ModelManager
    {
        public List<MakaleMenu> makaleMenu  { get; set; }
        public List<KategoriMenu> KategoriMenu { get; set; }
        public List<Private> logininfo{ get; set; }

        public int makalesayisi { get;set; }
    }
}

BlogSitesi/Models/Private.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlogSitesi.Models
{
    public class Private
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

BlogSitesi/Controllers/HomeController.cs
using BlogSitesi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogSitesi.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Blog()
        {
            //Verileri Sunucudan Çekip Model olarak viewe gönderiyoruz...
            ModelManager modelManager = new ModelManager();
            DataContext dataContext = new DataContext();
            List<MakaleMenu> makaleler=dataContext.makaleMenus.ToList();
            modelManager.makalesayisi = dataContext.makaleMenus.Count();
            modelManager.makaleMenu = makaleler;
            return View(modelManager);
        }

        
    }
}

BlogSitesi/Controllers/PrivateController.cs
using BlogSitesi.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogSitesi.Controllers
{
    public class PrivateController : Controller
    {
        [HttpGet]
        public ActionResult AdminPanel() {
        return View();
        }

        [HttpPost]
        public ActionResult AdminPanel(Private entity)
        {
            DataContext database = new DataContext();
            
            if (database.admin.Find(1)!= null)
            {
                var account = database.admin.Find(1);
                if (account.Username == entity.Username && account.Password == entity.Password)
                {
                    //Şifre Doğru girildiğinde gerçekleşicek
                    return View("Panel");
                }
                else
                {
                    //Şifre Yanlış Girildiğinde Gerçekleşecekler
                    return RedirectToAction("Blog", "Home");//Bu komut sayesinde ana dizine dönmek mümkün
                }
            }
            else
            {
                database.admin.Add(entity);
                database.SaveChanges();
                return View();
            }
            
        }

        [HttpPost]
        public ActionResult Panelveri(MakaleMenu entity)
        {
            DataContext database=new DataContext();
            database.makaleMenus.Add(entity);
            database.SaveChanges();
            return View("Panel");
        }
        
    }
}

BlogSitesi/Views/Home/Blog.cshtml
@model BlogSitesi.Models.ModelManager
@{
    ViewBag.Title = "Blog Sitesi";
}

@foreach (var makale in Model.makaleMenu)
{
    var bileske = "blog" + makale.Id;
    <div class="w3-card-4 w3-margin w3-white" id=@bileske style="margin-bottom:50px">
        <img src=@makale.image alt="Görsel" style="width:100%;">
        <div class="w3-container">
            <h3><b>@makale.makaleBaslik</b></h3>
            <h5>@makale.altBaslik, <span class="w3-opacity">@makale.makaleTarih</span></h5>
        </div>

        <div class="w3-container">
            <p style="text-align:justify">@makale.makaleIcerik</p>
            @if (makale.makaleButonIceriyormu == true)
            {
                <div class="w3-row" style="text-align: center;">

                    <p><a href=@makale.buttonLink target="_blank"><button class="w3-button w3-padding-large w3-white w3-border" style="border-radius:5px"><b>@makale.buttonText</b></button></a></p>

                </div>
            }

        </div>
    </div>
}

<br />

BlogSitesi/Views/Private/AdminPanel.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AdminPanel</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body style="text-align:center">
    <div class="container" style="max-width: 300px; margin: 120px auto">
            @using (Html.BeginForm("AdminPanel", "Private", FormMethod.Post))
            {
                <div class="w3-container" style="text-align:left">
                    <label class="w3-text-blue"><b>Username</b></label>
                    @Html.TextBox("Username", null, new { @class = "w3-input w3-border" })

                    <br />
                    <label class="w3-text-blue"><b>Password</b></label>
                    @Html.TextBox("Password", null, new { @class = "w3-input w3-border" })
                    <br />
                    <button class="w3-btn w3-blue" style="margin-top:5px">Login</button>
                </div>
            }
    </div>
</body>
</html>

BlogSitesi/Views/Private/Panel.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <title>Panel</title>
    <style>
        .textareapr{
            width:350px;
            height:150px;
        }

        .textboxpr {
            width: 250px;
           
        }
    </style>
</head>
<body>
    <div style="text-align:center;margin-bottom:50px">
        @Html.Partial("_succesbarPage")
        <hr />
        <h3>Gönderi Ekleme Alanı</h3>
        @using (Html.BeginForm("Panelveri", "Private", FormMethod.Post))
        {
            <div class="form-horizontal" style="font-size:10px">
                <div class="form-group">
                    <label for="exampleInputEmail1" class="control-label col-md-3">Resim URL</label>
                    <div class="col-md-9">
                        @Html.TextBox("image", null, new { @class = "textboxpr" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1" class="control-label col-md-3">Makale Başlık</label>
                    <div class="col-md-9">
                        @Html.TextBox("makaleBaslik", null, new { @class = "textboxpr" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1" class="control-label col-md-3">Alt Başlık</label>
                    <div class="col-md-9">
                        @Html.TextBox("altBaslik", null, new { @class = "textboxpr" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1" class="control-label col-md-3">Yayınlanma Tarihi</label>
                    <div class="col-md-9">
                        @Html.TextBox("makaleTarih", null, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1" class="control-label col-md-3">Makale İçeriği</label>
                    <div class="col-md-9">
                        @Html.TextArea("makaleIcerik", null, new { @class = "textareapr" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1" class="control-label col-md-3">Makale Buton İçeriyormu</label>
                    <div class="col-md-9">
                        Evet: @Html.RadioButton("makaleButonIceriyormu", true)
                        Hayır: @Html.RadioButton("makaleButonIceriyormu", false)
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1" class="control-label col-md-3">Button Text</label>
                    <div class="col-md-9">
                        @Html.TextBox("buttonText", null, new { @class = "textboxpr" })
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1" class="control-label col-md-3">Button Link</label>
                    <div class="col-md-9">
                        @Html.TextBox("buttonLink", null, new { @class = "textboxpr" })
                    </div>
                </div>
                <br />
                <button type="submit" class="btb btn-primary">Gönder</button>
            </div>
        }
    </div>
</body>
</html>

BlogSitesi/Views/Shared/_Layout.cshtml
@model BlogSitesi.Models.ModelManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link rel="icon" type="image/png" href="images/logo.ico">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Tamma+2&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        html {
            min-height: 100%;
        }

        body {
            min-height: 100%;
            padding-bottom: 0px !important;
            font-family: 'Baloo Tamma 2', cursive;
        }

        .minilogo {
            color: white !important;
        }

        .w3-button:hover {
            color: white !important;
            border-radius: 10px;
            background-color: #292989 !important;
        }

        .noHover:hover {
            background-color: #141414 !important;
            color: white !important;
        }

        .footer {
            position: relative;
            background-color: #f5f5f5;
            bottom: 0px;
            height: 60px;
            margin-top: -133px;
        }

        .navbarx {
            position: fixed;
            left: 0;
            top: 0;
            height: 100px;
            width: 100%;
            overflow: hidden;
            z-index: 999;
        }
    </style>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
</head>
<body>
    <header>
        
        <div class="navbarx w3-bar" style="background-color:#141414;color:white">
            <div class="w3-bar w3-card w3-left-align w3-large w3-hover-opacity-off" style="background-color:#141414;height: 30px;border-bottom: 0px solid gainsboro;">
                <p style="font-size:13px;padding-top:5px;margin-left:5px">Toplam Yazılan İçerik Sayısı: @Model.makalesayisi</p>
            </div>
            
            <a href="#" class="w3-bar-item w3-button noHover " style="margin-top:15px;height:40px;font-size:15px">L O G O</a>
            <a href="#" class="w3-bar-item w3-button " style="margin-top: 15px; height: 40px;">Link</a>
            <a href="#iletisim" class="w3-bar-item w3-button" style="margin-top: 15px; height: 40px;" >Link</a>
        </div>
    </header>

    <div class="w3-content" style="padding-top:60px;margin-bottom:133px;max-width:1400px;margin-top:60px">
       <div class="w3-row">
           <div class="w3-col l4">
               <div class="w3-card w3-margin w3-margin-top">
                   <img src="https://placehold.co/400x600" style="width:100%;max-height: 400px;">
                   <div class="w3-container w3-white">
                       <h4><b>Lorem Ipsum Dolor</b></h4>
                       <p style="text-align:justify;font-size:14px">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
                   </div>
               </div>

               <hr />
               <div class="w3-card w3-margin">
                   <div class="w3-container w3-padding">
                       <h4>Popüler Yayınlar</h4>
                   </div>
                   <ul class="w3-ul w3-hoverable w3-white">
                       <a href="#blog5" style="text-decoration: none;">
                       <li class="w3-padding-16">
                           <img src="https://toptankece.com/image/cache/catalog/urunler/ince-keceler/ince-kece-mavi-tonlar-2-320x320.jpg" alt="Image" class="w3-left w3-margin-right" style="width:50px;height: 50px;">
                           <span class="w3-large">Markalarım</span><br>
                           <span>Küçük Girişimler</span>
                       </li></a>
                       <a href="#blog8" style="text-decoration: none;">
                       <li class="w3-padding-16">
                           <img src="https://toptankece.com/image/cache/catalog/urunler/ince-keceler/ince-kece-mavi-tonlar-2-320x320.jpg" alt="Image" class="w3-left w3-margin-right" style="width:50px;height: 50px;">
                           <span class="w3-large">Endüstri Devrimleri</span><br>
                           <span>Devrimler ve Nitelikleri</span>
                       </li> </a>
                       <a href="#blog9" style="text-decoration: none;">
                       <li class="w3-padding-16">
                           <img src="https://toptankece.com/image/cache/catalog/urunler/ince-keceler/ince-kece-mavi-tonlar-2-320x320.jpg" alt="Image" class="w3-left w3-margin-right" style="width:50px;height: 50px;">
                           <span class="w3-large">DevOPS Nedir?</span><br>
                           <span>Geliştiriciler ve Operasyoncular</span>
                       </li></a>
                   </ul>
               </div>
               <div class="w3-card w3-margin" style="height:475px;margin-bottom:50px">
                   <div class="w3-container w3-padding">
                       <h4>Sosyal Medya</h4>
                   </div>
                   <iframe src="https://syndication.twitter.com/srv/timeline-profile/screen-name/elonmusk" style="width:100%;height:415px"></iframe>
               </div>




           </div>
           <div class="w3-col l8 s12">
               @RenderBody()
           </div>
       </div>
        <div style="background-color:#141414;width:95%;height:300px;margin:0 auto;border-radius:20px 220px 0px 0px;text-align:center;color:white;padding-top:50px" id="iletisim">
            <h4 style=" font-family: 'Baloo Tamma 2', cursive;">İletişim Bilgileri</h4><br />
            <i class="fa fa-phone" aria-hidden="true"></i> 05530000000<br /><br /><i class="fa fa-envelope" aria-hidden="true"></i> example@gmail.com<br />
            <br /><i class="fa fa-instagram minilogo" aria-hidden="true"></i>lorempisumdoor<br />

        </div>
    </div>
    <!--========================================================================================-->
    <footer class="footer" style="width:100%;background-color:#141414;height:200px;color:white;text-align:center">
        <p style="padding-top:80px">Bu Web Sitesi Abdulkerim Yenidoğan Tarafından Tasarlanmıştır! <br>Tüm Hakları Sakldırı 2023<br /><i class="fa fa-copyright" aria-hidden="true"></i></p>
    </footer>


</body>
</html>

BlogSitesi/Views/Shared/_succesbarPage.cshtml
<div class="w3-panel w3-green">
    <h3>Hoşgeldiniz Abdulkerim Bey,</h3>
    <p>Lütfen Güvenliğiniz gereği giriş Bilgilerinizi Kimseyle Paylaşmayınız...</p>
</div>